services:
  bot:
    image: tommy03/safebox
    volumes:
      - bot:/bot
    networks:
      - my-network
    env_file:
      - src/.env
  
  mongodb:
    image: mongo
    volumes:
      - configdb:/data/configdb
      - db:/data/db
    restart: always
    ports:
      - 27017:27017
    networks:
      - my-network
    env_file:
      - src/.env

volumes:
  bot:
  db:
  configdb:

networks:
  my-network:
    driver: bridge