services:
  
  bot:
    image: tommy03/safebox
    volumes:
      - storage:/bot/
    env_file:
      - .env
  
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env

volumes:
  storage: {}

networks:
  front-tier: {}
  back-tier: {}