services:
  bot:
    image: tommy03/safebox
    volumes:
      - bot:/bot
    env_file:
      - .env
  mongodb:
    image: mongo
    volumes:
      - configdb:/data/configdb
      - db:/data/db
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env

volumes:
  bot:
  db:
  configdb:

networks:
  front-tier: {}
  back-tier: {}