services:
  bot:
    build: .
    # image: tommy03/safebox
    volumes:
      - storage:/bot
    env_file:
      - .env
  mongodb:
    image: mongo
    volumes:
      - configdb:/data/configdb
      - db:/data/db
    restart: always
    env_file:
      - .env

volumes:
  storage:
  db:
  configdb:

networks:
  front-tier: {}
  back-tier: {}